name: Daily Agent Erwin Report

on:
  schedule:
    - cron: "0 3 * * *" # 8:30am IST is 03:00 UTC; runs daily at 8:30am IST
  workflow_dispatch: # (optional: allows manual runs)

jobs:
  stock-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily report
        env:
          GROWW_API_TOKEN: ${{ secrets.GROWW_API_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
          AGENT_ERWIN_BOT: ${{ secrets.AGENT_ERWIN_BOT }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python main.py
