name: Agent Erwin Daily Stock Report

on:
  schedule:
    - cron: "0 3 * * *" # Runs at 8:30 IST (3:00 UTC); adjust as needed
  workflow_dispatch: # Lets you run manually

jobs:
  daily-report:
    runs-on: ubuntu-latest
    env:
      GROWW_API_TOKEN: ${{ secrets.GROWW_API_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      AGENT_ERWIN_BOT: ${{ secrets.AGENT_ERWIN_BOT }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Agent Erwin daily report
        run: |
          python main.py
